[versions]
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
reactor-kotlin = "1.2.4"
kotlin-coroutines = "1.10.2"
r2dbc-pool = "1.0.2.RELEASE"
r2dbc-h2 = "1.1.0.RELEASE"
reactor = "3.7.12"
ktlint = "13.1.0"
kubernetes = "24.0.0"
aws-kotlin = "1.5.71"
mockk = "1.14.6"
commons-lang3 = "3.19.0"
slf4j = "2.0.17"
ktor = "3.3.1"
protobuf = "4.33.0"
protobuf-gradle = "0.9.5"

[libraries]
# R2DBC
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "r2dbc-pool" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2", version.ref = "r2dbc-h2" }

# Reactor
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactor-kotlin" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor" }

# Kotlin
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Kubernetes
kubernetes = { module = "io.kubernetes:client-java", version.ref = "kubernetes" }

# DynamoDB
aws-dynamodb = { module = "aws.sdk.kotlin:dynamodb", version.ref = "aws-kotlin" }

# MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Commons Lang
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

# SLF4J
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Ktor
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-protobuf = { module = "io.ktor:ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

# Protobuf
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle" }